version: "3.8"

services:
  pure_ftpd:
    # image: stilliard/pure-ftpd
    build:
      context: .
      args:
        BANNER: "---------- Welcome to SocialGouv Pure-FTPd [TLS] ----------"
    container_name: pure-ftpd
    # user: "1001:1001"
    ports:
      - "2121:2121"
      - "30000-30009:30000-30009"
    # volumes:
    #   - "$PWD/data:/home/test/"
      # - "$PWD/passwd:/etc/pure-ftpd/passwd"
      # # or ssl/tls with Let's Encrypt (cert and key as two files)
      # - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
      # - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: dev
      FTP_USER_PASS: dev
      FTP_USER_HOME: /home/ftpusers/user
      TLS_CN: "localhost"
      TLS_ORG: "SocialGouv"
      TLS_C: "FR"
      ADDED_FLAGS: "--tls=1 --verboselog"
      # # dev only
      TLS_USE_DSAPRAM: "true"
    restart: "no"
